-- V2__seed_ingredients.sql

INSERT INTO ingredient_regulation (inci_name, max_concentration, restricted, prohibited, conditions, product_types, regulation_ref)
VALUES
    ('SODIUM LAURYL SULFATE', 1.0, TRUE, FALSE, 'Max 1% in leave-on products', 'Soap,Shampoo,Conditioner', 'Annex III/49'),
    ('SODIUM LAURETH SULFATE', 3.0, FALSE, FALSE, 'Generally recognized as safe surfactant', 'Shampoo,Soap', NULL),
    ('COCAMIDOPROPYL BETAINE', 5.0, FALSE, FALSE, 'Amphoteric surfactant, may cause sensitization', 'Shampoo,Soap', NULL),
    ('SODIUM COCOYL ISETHIONATE', NULL, FALSE, FALSE, 'Mild surfactant', 'Soap,Shampoo', NULL),
    ('DISODIUM LAURETH SULFOSUCCINATE', NULL, FALSE, FALSE, 'Mild anionic surfactant', 'Shampoo', NULL),
    ('COCAMIDE MEA', NULL, FALSE, FALSE, 'Non-ionic surfactant / foam booster; may contain DEA impurities', 'Shampoo,Soap', NULL),
    ('SODIUM XYLENESULFONATE', NULL, FALSE, FALSE, 'Hydrotrope / solubilizer; no EU restriction', 'Shampoo,Soap', NULL),
    ('COCO-BETAINE', 5.0, FALSE, FALSE, 'Amphoteric surfactant derived from coconut', 'Shampoo,Soap', NULL),
    ('SODIUM LAUROYL ISETHIONATE', NULL, FALSE, FALSE, 'Mild anionic surfactant from coconut', 'Soap,Shampoo', NULL),
    ('COCO GLUCOSIDE', NULL, FALSE, FALSE, 'Mild non-ionic surfactant; sugar-derived', 'Shampoo,Soap', NULL),
    ('METHYLPARABEN', 0.4, TRUE, FALSE, 'Max 0.4% as acid; total parabens max 0.8%', 'Soap,Shampoo,Conditioner', 'Annex V/12'),
    ('PROPYLPARABEN', 0.14, TRUE, FALSE, 'Max 0.14% as acid; prohibited in leave-on for under 3', 'Soap,Shampoo,Conditioner', 'Annex V/12a'),
    ('BUTYLPARABEN', 0.14, TRUE, FALSE, 'Max 0.14% as acid', 'Soap,Shampoo,Conditioner', 'Annex V/12a'),
    ('PHENOXYETHANOL', 1.0, TRUE, FALSE, 'Max 1.0%', 'Soap,Shampoo,Conditioner', 'Annex V/29'),
    ('BENZALKONIUM CHLORIDE', 0.1, TRUE, FALSE, 'Max 0.1% in rinse-off products', 'Shampoo,Soap', 'Annex V/44'),
    ('METHYLISOTHIAZOLINONE', 0.0015, TRUE, FALSE, 'Max 0.0015% in rinse-off only; prohibited in leave-on', 'Shampoo,Soap', 'Annex V/57'),
    ('METHYLCHLOROISOTHIAZOLINONE', 0.0015, TRUE, FALSE, 'Max 0.0015% in rinse-off only (mixed with MIT 3:1)', 'Shampoo,Soap', 'Annex V/39'),
    ('DMDM HYDANTOIN', 0.6, TRUE, FALSE, 'Formaldehyde releaser; max 0.6%', 'Shampoo,Soap', 'Annex V/13'),
    ('IMIDAZOLIDINYL UREA', 0.6, TRUE, FALSE, 'Formaldehyde releaser; max 0.6%', 'Soap,Shampoo,Conditioner', 'Annex V/15'),
    ('SODIUM BENZOATE', 2.5, FALSE, FALSE, 'Max 2.5% as acid', 'Soap,Shampoo,Conditioner', 'Annex V/1'),
    ('POTASSIUM SORBATE', 0.6, FALSE, FALSE, 'Max 0.6% as acid', 'Soap,Shampoo,Conditioner', 'Annex V/4'),
    ('ETHYLHEXYLGLYCERIN', NULL, FALSE, FALSE, 'Preservative booster, no EU limit', 'Soap,Shampoo,Conditioner', NULL),
    ('BENZYL ALCOHOL', 1.0, TRUE, FALSE, 'Max 1.0% as preservative', 'Soap,Shampoo,Conditioner', 'Annex V/34'),
    ('FORMALDEHYDE', NULL, FALSE, TRUE, 'CMR Category 1B; prohibited as ingredient', 'Soap,Shampoo,Conditioner', 'Annex II/1577'),
    ('HYDROQUINONE', NULL, FALSE, TRUE, 'Prohibited in cosmetics (except hair dyes)', 'Soap,Shampoo', 'Annex II/1339'),
    ('COAL TAR', NULL, FALSE, TRUE, 'Prohibited; carcinogenic', 'Shampoo', 'Annex II/1395'),
    ('TRICLOSAN', 0.3, TRUE, FALSE, 'Max 0.3% in hand soaps, not allowed in other products', 'Soap', 'Annex V/25'),
    ('MERCURY', NULL, FALSE, TRUE, 'Prohibited', 'Soap,Shampoo,Conditioner', 'Annex II/221'),
    ('LEAD ACETATE', NULL, FALSE, TRUE, 'Prohibited', 'Shampoo', 'Annex II/289'),
    ('CHLOROFORM', NULL, FALSE, TRUE, 'Prohibited', 'Soap,Shampoo,Conditioner', 'Annex II/182'),
    ('BITHIONOL', NULL, FALSE, TRUE, 'Prohibited', 'Soap,Shampoo', 'Annex II/362'),
    ('BUTYLPHENYL METHYLPROPIONAL', NULL, FALSE, TRUE, 'Lilial; prohibited since 2022 (CMR substance)', 'Soap,Shampoo,Conditioner', 'Annex II/1666'),
    ('SALICYLIC ACID', 2.0, TRUE, FALSE, 'Max 2.0% in rinse-off hair products', 'Shampoo', 'Annex III/26'),
    ('ZINC PYRITHIONE', 1.0, TRUE, FALSE, 'Max 1.0% in rinse-off hair products only', 'Shampoo', 'Annex III/30'),
    ('KETOCONAZOLE', 2.0, TRUE, FALSE, 'Max 2.0% in anti-dandruff shampoos', 'Shampoo', 'Annex III'),
    ('GLYCOLIC ACID', 4.0, TRUE, FALSE, 'Max 4.0%, pH >= 3.5', 'Soap,Shampoo', 'Annex III/28'),
    ('RETINOL', 0.3, TRUE, FALSE, 'Max 0.3% Retinol equivalent in body products', 'Soap', 'Annex III'),
    ('RETINYL PALMITATE', 0.55, TRUE, FALSE, 'Max 0.055% as Retinol equivalent in body', 'Soap', 'Annex III'),
    ('HYDROGEN PEROXIDE', 12.0, TRUE, FALSE, 'Max 12% in hair products', 'Shampoo,Conditioner', 'Annex III/12'),
    ('SELENIUM DISULFIDE', 1.0, TRUE, FALSE, 'Max 1% in anti-dandruff shampoos', 'Shampoo', 'Annex III/49'),
    ('PIROCTONE OLAMINE', 1.0, FALSE, FALSE, 'Max 1.0% anti-dandruff agent', 'Shampoo', 'Annex III'),
    ('CLIMBAZOLE', 0.5, TRUE, FALSE, 'Max 0.5% in rinse-off products', 'Shampoo', 'Annex III/54'),
    ('CIMBAZOLE', 0.5, TRUE, FALSE, 'Alternate spelling of Climbazole; Max 0.5% in rinse-off', 'Shampoo', 'Annex III/54'),
    ('LACTIC ACID', 2.5, TRUE, FALSE, 'Max 2.5% in leave-on; no limit in rinse-off at pH >= 3.5', 'Shampoo,Soap,Conditioner', 'Annex III/28'),
    ('MENTHOL', NULL, FALSE, FALSE, 'Cooling agent; no EU restriction', 'Shampoo,Soap,Conditioner', NULL),
    ('GLYCERIN', NULL, FALSE, FALSE, 'Humectant; no restriction', 'Soap,Shampoo,Conditioner', NULL),
    ('DIMETHICONE', NULL, FALSE, FALSE, 'Silicone conditioner; no restriction', 'Shampoo,Conditioner', NULL),
    ('DIMETHICONOL', NULL, FALSE, FALSE, 'Silicone conditioning agent; no restriction', 'Shampoo,Conditioner', NULL),
    ('AMODIMETHICONE', NULL, FALSE, FALSE, 'Amino-functional silicone; selective conditioning', 'Shampoo,Conditioner', NULL),
    ('POLYDIMETHYLSILOXANE', NULL, FALSE, FALSE, 'Silicone polymer (PDMS); conditioning, no EU restriction', 'Shampoo,Conditioner', NULL),
    ('PANTHENOL', NULL, FALSE, FALSE, 'Pro-vitamin B5; no restriction', 'Shampoo,Conditioner', NULL),
    ('CETYL ALCOHOL', NULL, FALSE, FALSE, 'Fatty alcohol emollient', 'Conditioner,Soap', NULL),
    ('STEARYL ALCOHOL', NULL, FALSE, FALSE, 'Fatty alcohol emollient', 'Conditioner,Soap', NULL),
    ('CETEARYL ALCOHOL', NULL, FALSE, FALSE, 'Emulsifying fatty alcohol', 'Conditioner,Shampoo', NULL),
    ('TOCOPHEROL', NULL, FALSE, FALSE, 'Vitamin E; antioxidant', 'Soap,Shampoo,Conditioner', NULL),
    ('ALOE BARBADENSIS LEAF JUICE', NULL, FALSE, FALSE, 'Aloe vera; skin soothing', 'Soap,Shampoo,Conditioner', NULL),
    ('ARGAN OIL', NULL, FALSE, FALSE, 'Conditioning oil', 'Shampoo,Conditioner', NULL),
    ('COCONUT OIL', NULL, FALSE, FALSE, 'COCOS NUCIFERA OIL; no restriction', 'Soap,Shampoo,Conditioner', NULL),
    ('SHEA BUTTER', NULL, FALSE, FALSE, 'BUTYROSPERMUM PARKII BUTTER', 'Soap,Conditioner', NULL),
    ('SHEA OIL', NULL, FALSE, FALSE, 'BUTYROSPERMUM PARKII OIL; emollient', 'Soap,Conditioner', NULL),
    ('JOJOBA OIL', NULL, FALSE, FALSE, 'SIMMONDSIA CHINENSIS SEED OIL', 'Shampoo,Conditioner', NULL),
    ('MINERAL OIL', NULL, FALSE, FALSE, 'PARAFFINUM LIQUIDUM; emollient, no EU restriction', 'Soap,Shampoo,Conditioner', NULL),
    ('GLYCOL DISTEARATE', NULL, FALSE, FALSE, 'Pearlescent agent / emollient; no EU restriction', 'Shampoo,Soap', NULL),
    ('STEARIC ACID', NULL, FALSE, FALSE, 'Fatty acid emulsifier; no restriction', 'Soap,Conditioner', NULL),
    ('ROSEMARY OIL', NULL, FALSE, FALSE, 'ROSMARINUS OFFICINALIS LEAF OIL; hair conditioning', 'Shampoo,Conditioner', NULL),
    ('TEA TREE OIL', NULL, FALSE, FALSE, 'MELALEUCA ALTERNIFOLIA LEAF OIL; antimicrobial properties', 'Shampoo,Soap', NULL),
    ('EMBLICA OFFICINALIS', NULL, FALSE, FALSE, 'Amla extract; hair conditioning, no EU restriction', 'Shampoo,Conditioner', NULL),
    ('HIBISCUS ROSA-SINENSIS', NULL, FALSE, FALSE, 'Hibiscus flower extract; hair conditioning', 'Shampoo,Conditioner', NULL),
    ('SAPINDUS TRIFOLIATUS', NULL, FALSE, FALSE, 'Reetha/Soapnut extract; natural surfactant', 'Shampoo,Soap', NULL),
    ('TRIGONELLA FOENUM-GRAECUM', NULL, FALSE, FALSE, 'Fenugreek (Methi) seed extract; hair conditioning', 'Shampoo,Conditioner', NULL),
    ('LAWSONIA INERMIS', NULL, FALSE, FALSE, 'Henna leaf extract; colourant/conditioner', 'Shampoo,Conditioner', NULL),
    ('PRUNUS AMYGDALUS', NULL, FALSE, FALSE, 'Almond (Badam) kernel extract; emollient', 'Shampoo,Conditioner,Soap', NULL),
    ('GLYCYRRHIZA GLABRA', NULL, FALSE, FALSE, 'Mulethi/Licorice root extract; soothing agent', 'Shampoo,Conditioner', NULL),
    ('ECLIPTA ALBA', NULL, FALSE, FALSE, 'Bhringraj plant oil extract; traditional hair care', 'Shampoo,Conditioner', NULL),
    ('ALOE BARBADENSIS', NULL, FALSE, FALSE, 'Aloe vera / Kumari; soothing and moisturizing', 'Shampoo,Conditioner,Soap', NULL),
    ('CITRIC ACID', NULL, FALSE, FALSE, 'pH adjuster; no restriction', 'Soap,Shampoo,Conditioner', NULL),
    ('SODIUM HYDROXIDE', 5.0, TRUE, FALSE, 'Max 5% in hair straighteners', 'Soap,Shampoo', 'Annex III/15a'),
    ('SODIUM CHLORIDE', NULL, FALSE, FALSE, 'Viscosity modifier; no restriction', 'Shampoo,Soap', NULL),
    ('SODIUM CITRATE', NULL, FALSE, FALSE, 'Buffering / chelating agent; no restriction', 'Shampoo,Soap,Conditioner', NULL),
    ('SODIUM PALMITATE', NULL, FALSE, FALSE, 'Soap base salt (sodium salt of palmitic acid); no restriction', 'Soap', NULL),
    ('TETRASODIUM EDTA', NULL, FALSE, FALSE, 'Chelating agent; stabilizer; no EU cosmetic restriction', 'Shampoo,Soap,Conditioner', NULL),
    ('PARFUM', NULL, FALSE, FALSE, 'Fragrance; allergens must be declared if above threshold', 'Soap,Shampoo,Conditioner', 'Annex III/67-92'),
    ('CARBOMER', NULL, FALSE, FALSE, 'Thickener / viscosity controller; no restriction', 'Shampoo,Soap,Conditioner', NULL),
    ('PEG-90M', NULL, FALSE, FALSE, 'Thickener / film former; no restriction', 'Shampoo,Conditioner', NULL),
    ('PPG-5-CETETH-20', NULL, FALSE, FALSE, 'Emulsifier / solubilizer; no EU restriction', 'Shampoo,Conditioner', NULL),
    ('LAURETH-4', NULL, FALSE, FALSE, 'Non-ionic surfactant / emulsifier; no restriction', 'Shampoo,Conditioner', NULL),
    ('TITANIUM DIOXIDE', NULL, TRUE, FALSE, 'CI 77891; restricted as colourant in certain forms', 'Soap,Shampoo', 'Annex IV'),
    ('POLYQUATERNIUM-7', NULL, FALSE, FALSE, 'Conditioning polymer', 'Shampoo,Conditioner', NULL),
    ('POLYQUATERNIUM-10', NULL, FALSE, FALSE, 'Anti-static agent', 'Shampoo,Conditioner', NULL),
    ('GUAR HYDROXYPROPYLTRIMONIUM CHLORIDE', NULL, FALSE, FALSE, 'Conditioning polymer', 'Shampoo,Conditioner', NULL),
    ('PEG-150 DISTEARATE', NULL, FALSE, FALSE, 'Thickener/emulsifier', 'Shampoo', NULL),
    ('COCODIMONIUM HYDROXYPROPYL HYDROLYZED WHEAT PROTEIN', NULL, FALSE, FALSE, 'Protein conditioning agent', 'Shampoo,Conditioner', NULL),
    ('2-OLEAMIDO-1,3-OCTADECANE DIOL', NULL, FALSE, FALSE, 'Ceramide analog; hair repair agent; no restriction', 'Shampoo,Conditioner', NULL),
    ('LIMONENE', NULL, TRUE, FALSE, 'Fragrance allergen; must be declared above 0.01% rinse-off / 0.001% leave-on', 'Soap,Shampoo,Conditioner', 'Annex III/67'),
    ('LINALOOL', NULL, TRUE, FALSE, 'Fragrance allergen; must be declared above 0.01% rinse-off / 0.001% leave-on', 'Soap,Shampoo,Conditioner', 'Annex III/74'),
    ('HEXYL CINNAMAL', NULL, TRUE, FALSE, 'Fragrance allergen; must be declared above threshold', 'Soap,Shampoo,Conditioner', 'Annex III/72'),
    ('BENZYL SALICYLATE', NULL, TRUE, FALSE, 'Fragrance allergen; must be declared above threshold', 'Soap,Shampoo,Conditioner', 'Annex III/85'),
    ('CI 19140', NULL, TRUE, FALSE, 'Tartrazine yellow; must be listed, allergen risk', 'Shampoo,Soap', 'Annex IV'),
    ('CI 17200', NULL, TRUE, FALSE, 'Red 33; restricted colorant', 'Shampoo,Soap', 'Annex IV'),
    ('CI 16035', NULL, TRUE, FALSE, 'Allura Red AC; permitted food/cosmetic colorant', 'Shampoo,Soap', 'Annex IV'),
    ('QUINAZARINE GREEN SS', NULL, TRUE, FALSE, 'Green dye; limited to rinse-off products', 'Shampoo', 'Annex IV'),
    ('QUINOLINE YELLOW WS', NULL, TRUE, FALSE, 'CI 47005; yellow dye; restricted colorant', 'Shampoo,Soap', 'Annex IV'),
    ('TONEY RED', NULL, TRUE, FALSE, 'Red dye colourant for cosmetics', 'Shampoo,Soap', 'Annex IV')
ON CONFLICT (inci_name) DO UPDATE SET
    max_concentration = EXCLUDED.max_concentration,
    restricted = EXCLUDED.restricted,
    prohibited = EXCLUDED.prohibited,
    conditions = EXCLUDED.conditions,
    product_types = EXCLUDED.product_types,
    regulation_ref = EXCLUDED.regulation_ref;

INSERT INTO combination_rule (ingredient_a, ingredient_b, condition_desc, safe_concentration_a, required_concentration_b, explanation, source)
VALUES
    ('METHYLPARABEN', 'PROPYLPARABEN', 'Combined parabens must not exceed 0.8% total', 0.4, 0.14, 'When both parabens are present, total concentration of all parabens (as acid) must not exceed 0.8%. Individual limits also apply.', 'EU Reg. (EC) 1223/2009, Annex V/12'),
    ('SODIUM LAURYL SULFATE', 'METHYLISOTHIAZOLINONE', 'SLS enhances penetration of sensitizing preservatives', 1.0, 0.0015, 'SLS disrupts skin barrier, increasing penetration of MIT. Combined use increases sensitization risk significantly.', 'SCCS/1521/13'),
    ('SALICYLIC ACID', 'GLYCOLIC ACID', 'Dual acid combination — pH and total concentration critical', 2.0, 4.0, 'Combined AHA/BHA increases exfoliation intensity. Total acid concentration must be managed; pH must remain >= 3.5.', 'SCCS/1629/21'),
    ('METHYLCHLOROISOTHIAZOLINONE', 'METHYLISOTHIAZOLINONE', 'Must be used in 3:1 ratio; max combined 0.0015%', 0.0015, 0.0015, 'MCI and MIT must be used together in 3:1 ratio (MCI:MIT). Maximum combined concentration 0.0015% in rinse-off only.', 'EU Reg. Annex V/39'),
    ('PHENOXYETHANOL', 'ETHYLHEXYLGLYCERIN', 'Synergistic preservative system', 1.0, NULL, 'Ethylhexylglycerin boosts phenoxyethanol''s antimicrobial activity. This allows lower effective concentrations. No violation — beneficial combination.', 'Cosmetic preservation best practices'),
    ('SODIUM HYDROXIDE', 'HYDROGEN PEROXIDE', 'Strongly reactive combination', 5.0, 12.0, 'NaOH and H2O2 together cause exothermic reaction. Must be carefully buffered in hair treatments. pH and concentration controls essential.', 'SCCS/1553/15'),
    ('RETINOL', 'SALICYLIC ACID', 'Increased irritation potential', 0.3, 2.0, 'Retinol combined with Salicylic Acid significantly increases skin irritation and photosensitivity. Not recommended in same leave-on product.', 'Dermatological consensus / SCCS opinion'),
    ('RETINOL', 'GLYCOLIC ACID', 'Increased irritation and photosensitivity', 0.3, 4.0, 'AHA + Retinoid combination dramatically increases skin irritation. Should not be used in same leave-on product.', 'Dermatological consensus'),
    ('FORMALDEHYDE', 'DMDM HYDANTOIN', 'Double formaldehyde exposure', NULL, 0.6, 'DMDM Hydantoin releases formaldehyde. If free formaldehyde is also present, combined exposure far exceeds safe limits.', 'EU Reg. Annex II/1577 + Annex V/13'),
    ('TRICLOSAN', 'SODIUM LAURYL SULFATE', 'Enhanced systemic absorption', 0.3, 1.0, 'SLS increases dermal penetration of Triclosan, raising concerns about endocrine disruption at sub-threshold concentrations.', 'Environmental Health Perspectives'),
    ('ZINC PYRITHIONE', 'SELENIUM DISULFIDE', 'Incompatible anti-dandruff actives', 1.0, 1.0, 'Both are anti-dandruff actives with different mechanisms. Combined use provides no benefit and increases scalp irritation.', 'Dermatological formulary guidance'),
    ('BENZALKONIUM CHLORIDE', 'SODIUM LAURYL SULFATE', 'Cationic-anionic incompatibility', 0.1, 1.0, 'Cationic (BAC) and anionic (SLS) surfactants form insoluble precipitates, reducing efficacy of both and causing product instability.', 'Surfactant chemistry principles'),
    ('SALICYLIC ACID', 'LACTIC ACID', 'Dual acid combination — enhanced exfoliation risk', 2.0, 2.5, 'BHA + AHA combination lowers effective pH significantly. Combined use increases irritation potential. Monitor total acid concentration and pH.', 'SCCS guidance on AHA/BHA products'),
    ('SODIUM LAURYL SULFATE', 'DIMETHICONE', 'Surfactant-silicone interaction in shampoos', 1.0, NULL, 'SLS can strip silicone buildup but also increases scalp dryness. High SLS with heavy silicones may cause residue buildup requiring clarifying.', 'Cosmetic chemistry formulation guidance'),
    ('BUTYLPHENYL METHYLPROPIONAL', 'LINALOOL', 'Double fragrance allergen exposure', NULL, NULL, 'Both are significant fragrance allergens. Combined presence increases risk of contact sensitization. Butylphenyl methylpropional (Lilial) is now prohibited in EU.', 'SCCS/1459/11 + EU Reg. Annex II/1666');
